# Website: https://www.firefly-iii.org/
# Container:
#  - Core: https://hub.docker.com/r/fireflyiii/core
#  - DB: https://hub.docker.com/r/fireflyiii/mariadb
#  - Importer: https://hub.docker.com/r/fireflyiii/data-importer
#  - Cron: https://hub.docker.com/r/alpine
# GitHub: https://github.com/firefly-iii/firefly-iii/

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - <dir>:/var/www/html/storage/upload
    env_file: stack.env
    networks:
      - firefly_iii
      - nginprox
    #ports:
    #  - 80:8080
    depends_on:
      - db

  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: stack.env
    networks:
      - firefly_iii
    volumes:
      - <dir>:/var/lib/mysql
  
  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
      - nginprox
    #ports:
    #  - '81:8080'
    depends_on:
      - app
    env_file: stack.env
  
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace PLEASE_REPLACE_WITH_32_CHAR_CODE below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: stack.env
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/<APP_KEY secret>;echo\" 
      | crontab - 
      && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
  nginprox:
    external: true
    name: nginprox