services:
  nebula-sync:
    # Website: n/a
    # Docker Hub: https://hub.docker.com/r/lovelaze/nebula-sync
    # GitHub: https://github.com/lovelaze/nebula-sync
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
      # PRIMARY=<http://172.0.1.1:8008|<password>>
      # REPLICAS=<http://172.0.1.2:8008|<password>,http://172.0.1.3:8008|<password>
      # FULL_SYNC=<false | true>
      # RUN_GRAVITY=<true | flase>
      # CRON=<cron format 30 * * * *>
      # TZ=<https://en.wikipedia.org/wiki/List_of_tz_database_time_zones>
      # CLIENT_SKIP_TLS_VERIFICATION=<true | false>
      # CLIENT_RETRY_DELAY_SECONDS=<10>
      # CLIENT_TIMEOUT_SECONDS=<60>
      # SYNC_CONFIG_DNS=<true | false>
      # SYNC_CONFIG_DHCP=<false | true>
      # SYNC_CONFIG_NTP=<false | true>
      # SYNC_CONFIG_RESOLVER=<false | true>
      # SYNC_CONFIG_DATABASE=<false | true>
      # SYNC_CONFIG_MISC=<false | true>
      # SYNC_CONFIG_DEBUG=<false | true>
      # SYNC_GRAVITY_DHCP_LEASES=<true | false>
      # SYNC_GRAVITY_GROUP=<true | false>
      # SYNC_GRAVITY_AD_LIST=<true | false>
      # SYNC_GRAVITY_AD_LIST_BY_GROUP=<true | false>
      # SYNC_GRAVITY_DOMAIN_LIST=<true | false>
      # SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=<true | false>
      # SYNC_GRAVITY_CLIENT=<true | false>
      # SYNC_GRAVITY_CLIENT_BY_GROUP=<true | false>
      # SYNC_CONFIG_DNS_EXCLUDE=<upstreams>
      # NS_DEBUG=<false | true>
      PRIMARY: ${PRIMARY}
      REPLICAS: ${REPLICAS}
      FULL_SYNC: ${FULL_SYNC}
      RUN_GRAVITY: ${RUN_GRAVITY}
      CRON: ${CRON}
      TZ: ${TZ}
      CLIENT_SKIP_TLS_VERIFICATION: ${CLIENT_SKIP_TLS_VERIFICATION}
      CLIENT_RETRY_DELAY_SECONDS: ${CLIENT_RETRY_DELAY_SECONDS}
      CLIENT_TIMEOUT_SECONDS: ${CLIENT_TIMEOUT_SECONDS}
      SYNC_CONFIG_DNS: ${SYNC_CONFIG_DNS}
      SYNC_CONFIG_DHCP: ${SYNC_CONFIG_DHCP}
      SYNC_CONFIG_NTP: ${SYNC_CONFIG_NTP}
      SYNC_CONFIG_RESOLVER: ${SYNC_CONFIG_RESOLVER}
      SYNC_CONFIG_DATABASE: ${SYNC_CONFIG_DATABASE}
      SYNC_CONFIG_MISC: ${SYNC_CONFIG_MISC}
      SYNC_CONFIG_DEBUG: ${SYNC_CONFIG_DEBUG}
      SYNC_GRAVITY_DHCP_LEASES: ${SYNC_GRAVITY_DHCP_LEASES}
      SYNC_GRAVITY_GROUP: ${SYNC_GRAVITY_GROUP}
      SYNC_GRAVITY_AD_LIST: ${SYNC_GRAVITY_AD_LIST}
      SYNC_GRAVITY_AD_LIST_BY_GROUP: ${SYNC_GRAVITY_AD_LIST_BY_GROUP}
      SYNC_GRAVITY_DOMAIN_LIST: ${SYNC_GRAVITY_DOMAIN_LIST}
      SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: ${SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP}
      SYNC_GRAVITY_CLIENT: ${SYNC_GRAVITY_CLIENT}
      SYNC_GRAVITY_CLIENT_BY_GROUP: ${SYNC_GRAVITY_CLIENT_BY_GROUP}
      SYNC_CONFIG_DNS_EXCLUDE: ${SYNC_CONFIG_DNS_EXCLUDE}
      NS_DEBUG: ${NS_DEBUG}
    dns:
      - <1.1.1.1>
      - <1.0.0.1>
