# Website: n/a
# Container: https://hub.docker.com/r/lovelaze/nebula-sync
# GitHub: https://github.com/lovelaze/nebula-sync

services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    environment:
      PRIMARY: ${PRIMARY}
      REPLICAS: ${REPLICAS}
      FULL_SYNC: ${FULL_SYNC}
      RUN_GRAVITY: ${RUN_GRAVITY}
      CRON: ${CRON}
      TZ: ${TZ}
      CLIENT_SKIP_TLS_VERIFICATION: ${CLIENT_SKIP_TLS_VERIFICATION}
      CLIENT_RETRY_DELAY_SECONDS: ${CLIENT_RETRY_DELAY_SECONDS}
      CLIENT_TIMEOUT_SECONDS: ${CLIENT_TIMEOUT_SECONDS}
      SYNC_CONFIG_DNS: ${SYNC_CONFIG_DNS}
      SYNC_CONFIG_DHCP: ${SYNC_CONFIG_DHCP}
      SYNC_CONFIG_NTP: ${SYNC_CONFIG_NTP}
      SYNC_CONFIG_RESOLVER: ${SYNC_CONFIG_RESOLVER}
      SYNC_CONFIG_DATABASE: ${SYNC_CONFIG_DATABASE}
      SYNC_CONFIG_MISC: ${SYNC_CONFIG_MISC}
      SYNC_CONFIG_DEBUG: ${SYNC_CONFIG_DEBUG}
      SYNC_GRAVITY_DHCP_LEASES: ${SYNC_GRAVITY_DHCP_LEASES}
      SYNC_GRAVITY_GROUP: ${SYNC_GRAVITY_GROUP}
      SYNC_GRAVITY_AD_LIST: ${SYNC_GRAVITY_AD_LIST}
      SYNC_GRAVITY_AD_LIST_BY_GROUP: ${SYNC_GRAVITY_AD_LIST_BY_GROUP}
      SYNC_GRAVITY_DOMAIN_LIST: ${SYNC_GRAVITY_DOMAIN_LIST}
      SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: ${SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP}
      SYNC_GRAVITY_CLIENT: ${SYNC_GRAVITY_CLIENT}
      SYNC_GRAVITY_CLIENT_BY_GROUP: ${SYNC_GRAVITY_CLIENT_BY_GROUP}
      SYNC_CONFIG_DNS_EXCLUDE: ${SYNC_CONFIG_DNS_EXCLUDE}
      NS_DEBUG: ${NS_DEBUG}
    dns:
      - <1.1.1.1>
      - <1.0.0.1>
