# Website: https://omnitools.app/
# Container: https://hub.docker.com/r/iib0011/omni-tools
# GitHub: https://github.com/iib0011/omni-tools

services:
  omni-tools:
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    restart: unless-stopped
    #ports:
      #- "8080:80"

networks:
  default:
    external: true
    name: proxnet