# Website: https://pi-hole.net/
# Container: https://hub.docker.com/r/pihole/pihole
# GitHub: https://github.com/pi-hole/docker-pi-hole

services:
  pihole:
    container_name: pihole
    hostname: starbase-epsilon
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8008:80/tcp"
      - "4438:443/tcp"
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      FTLCONF_webserver_session_timeout: ${FTLCONF_webserver_session_timeout}
      #FTLCONF_webserver_api_app_sudo: ${FTLCONF_webserver_api_app_sudo}
      #FTLCONF_dns_upstreams: ${FTLCONF_dns_upstreams}
      #FTLCONF_dns_domain: ${FTLCONF_dns_domain}
      #FTLCONF_dns_dnssec: ${FTLCONF_dns_dnssec}
      #FTLCONF_dns_rateLimit_count: ${FTLCONF_dns_rateLimit_count}
      #FTLCONF_dns_ignoreLocalhost: ${FTLCONF_dns_ignoreLocalhost}
      #FTLCONF_dns_listeningMode: ${FTLCONF_dns_listeningMode}
