# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    # Website: https://pi-hole.net/
    # Docker Hub: https://hub.docker.com/r/pihole/pihole
    # GitHub: https://github.com/pi-hole/docker-pi-hole
    image: pihole/pihole:latest
    container_name: pihole
    hostname: starbase-epsilon
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8008:80/tcp"
      - "4438:443/tcp"
    environment:
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      TZ: ${TZ}
      FTLCONF_webserver_session_timeout: ${FTLCONF_webserver_session_timeout}
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE