# Website: https://gethomepage.dev/
# Container: https://ghcr.io/gethomepage/homepage
# GitHub: https://github.com/gethomepage/homepage

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    restart: unless-stopped
    #ports:
      #- 3000:3000
    volumes:
      - /<localpath>/homepage/:/app/config # Make sure your local config directory exists
      - /<localpath>/homepage/images/:/app/public/images # images folder
      - /<localpath>/homepage/images/icons/:/app/public/icons # icons folder
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS} # Needs to be set to the sub.domain.tld or IP address you will access Homepage from

networks:
  default:
    external: true
    name: proxnet