# Website: https://gethomepage.dev/
# Container: https://ghcr.io/gethomepage/homepage
# GitHub: https://github.com/gethomepage/homepage


services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    restart: unless-stopped
    #ports:
      #- 3000:3000
    volumes:
      - /<location>/docker/homepage:/app/config # Make sure your local config directory exists
      - /<location>/docker/homepage/images:/app/public/images # images folder
      - /<location>/docker/homepage/images/icons:/app/public/icons # icons folder
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}

networks:
  default:
    external: true
    name: nginprox
