# https://gethomepage.dev/configs/services/

# Row 1, Column 1
- Services:
  - Zone1:
      - Uptime Kuma:
          href: http://kuma.domain.tld
          icon: sh-uptime-kuma.svg
          server: <host>
          container: uptime-kuma
          widget:
            type: uptimekuma
            fields: ["up", "down", "uptime"]
            url: http://kuma.domain.tld
            slug: all
      - Nginx Proxy Manager:
          href: http://npm.domain.tld
          icon: sh-nginx-proxy-manager.svg
          server: <host>
          container: nginproxy
          widget:
            type: npm
            fields: ["enabled", "disabled", "total"]
            url: http://npm.domain.tld
            username: <secret>
            password: <secret>
      - Wireguard:
          href: http://vpn.domain.tld
          icon: sh-wireguard.svg
          server: <host>
          container: wg-easy
          widget:
            type: wgeasy
            fields: ["connected", "enabled", "disabled", "total"]
            url: http://vpn.domain.tld
            password: <secret>
            threshold: 2

# Row 1, Column 2
  - Zone2:
      - Host 1:
          href: http://portainer.domain.tld/#!/#/docker/dashboard
          icon: sh-portainer.svg
          server: <host>
          container: portainer
          widget:
            type: portainer
            fields: ["running", "stopped", "total"]
            url: http://portainer.domain.tld
            env: 6
            key: <secret>
      - Host 2 (Agent):
          href: http://portainer.domain.tld/#!/#/docker/dashboard
          icon: sh-portainer.svg
          server: <host>
          container: portainer_agent
          widget:
            type: portainer
            fields: ["running", "stopped", "total"]
            url: http://portainer.domain.tld
            env: 7
            key: <secret>
      - Host 3 (Agent):
          href: http://portainer.domain.tld/#!/#/docker/dashboard
          icon: sh-portainer.svg
          server: delta
          container: portainer_agent
          widget:
            type: portainer
            fields: ["running", "stopped", "total"]
            url: http://portainer.domain.tld
            env: #
            key: <secret>

# Row 1, Column 3
  - Zone3:
      - Primary DNS:
          href: http://dns1.domain.tld
          icon: sh-pi-hole.svg
          widget:
            type: pihole
            fields: ["queries", "blocked", "blocked_percent", "gravity"]
            url: http://dns1.domain.tld
            version: 6
            key: <secret>
      - Secondary DNS:
          href: http://dns2.domain.tld
          icon: sh-pi-hole.svg
          server: <host>
          container: pihole
          widget:
            type: pihole
            fields: ["queries", "blocked", "blocked_percent", "gravity"]
            url: http://dns2.domain.tld
            version: 6
            key: <secret>
      - Nebula Sync:
          icon: sh-pi-hole.svg
          server: <host>
          container: nebula-sync

# Row 1, Column 4
  - Zone4:
      - Diun - Host 1:
          icon: sh-diun.webp
          server: <host>
          container: diun
      - Diun - Host 2:
          icon: sh-diun.webp
          server: <host>
          container: diun
      - Diun - Host 3:
          icon: sh-diun.webp
          server: wanderer
          container: diun
      - Watchtower - Host:
          icon: sh-watchtower.svg
          server: <host>
          container: watchtower

# Row 2, Column 1
- Row2:
  - Col1:
      - Calendar:
          widget:
            type: calendar
            firstDayInWeek: sunday
            maxEvents: none
            view: monthly
            integrations:
              - type: ical
                url: https://calendar.google.com/<secret>/basic.ics
                name: Calendar

# Row 2, Column 2
  - Col2:
    - Agenda:
        widget:
          type: calendar
          view: agenda
          showTime: true
          maxEvents: 11
          integrations:
           - type: ical
             url: https://calendar.google.com/<secret>/basic.ics
             name: Agenda

# Row 2, Column 3
  - Col3:
      - Karakeep:
          href: https://keep.domain.tld
          icon: sh-karakeep-light.svg
          server: <host>
          container: karakeep_web
          widget:
            type: karakeep
            fields: ["bookmarks", "highlights", "lists", "tags"]
            url: https://keep.domain.tld
            key: <secret>
      - HomeBox:
          href: http://homebox.domain.tld
          icon: sh-homebox.svg
          server: <host>
          container: homebox
          widget:
            type: homebox
            fields: ["items", "locations", "totalValue"]
            url: http://homebox.domain.tld
            username: <secret>
            password: <secret>

# Row 2, Column 4
  - Col4:
      - Skynet Reader:
          href: https://rss.domain.tld
          icon: sh-freshrss.svg
          server: <host>
          container: freshrss
          widget:
            type: freshrss
            fields: ["subscriptions", "unread"]
            url: https://rss.domain.tld
            username: <secret>
            password: <secret>
            
# Row 3
- Bitwarden:
    - Admin:
        icon: sh-bitwarden.svg
        server: <host>
        container: bitwarden-admin
    - API:
        icon: sh-microsoft-azure.svg
        server: <host>
        container: bitwarden-api
    - Attachments:
        icon: sh-papra.svg
        server: <host>
        container: bitwarden-attachments
    - Events:
        icon: sh-nextcloud-calendar.svg
        server: <host>
        container: bitwarden-events
    - Icons:
        icon: sh-hashicorp-vault.svg
        server: <host>
        container: bitwarden-icons
    - Identity:
        icon: sh-google.svg
        server: <host>
        container: bitwarden-identity
    - MSSQL:
        icon: sh-microsoft-access.svg
        server: <host>
        container: bitwarden-mssql
    - Nginx:
        icon: sh-nginx.svg
        server: <host>
        container: bitwarden-nginx
    - Notifications:
        icon: sh-notifiarr.png
        server: <host>
        container: bitwarden-notifications
    - SSO:
        icon: sh-microsoft.svg
        server: <host>
        container: bitwarden-sso
    - Web:
        icon: sh-web-check.png
        server: <host>
        container: bitwarden-web

#Row 4
- Containers:
    - Karakeep Chrome:
        icon: sh-karakeep-light.svg
        container: karakeep_chrome
        server: <host>
    - Karakeep Meilisearch:
        icon: sh-karakeep-light.svg
        container: karakeep_meilisearch
        server: <host>
    - Wandering Wiki:
        icon: sh-wiki-js.svg
        href: http://wiki.domain.tld
        server: <host>
        container: wikijs-wiki
    - Wandering Wiki Database:
        icon: sh-postgresql.svg
        server: <host>
        container: wikijs-db
    - ConvertX:
        href: http://convertx.domain.tld
        icon: sh-convertx.webp
        server: <host>
        container: convertx
    - DateTime:
        href: https://datetime.domain.tld
        icon: sh-leantime.svg
        server: <host>
        container: datetime
    - IT Tools:
        href: https://ittools.domain.tld
        icon: sh-it-tools.svg
        server: <host>
        container: ittools
    - Omni Tools:
        href: http://omnitools.domain.tld
        icon: sh-omnitools.webp
        server: <host>
        container: omni-tools