# https://gethomepage.dev/configs/services/

- Skynet Services:
  - Skynet1:
      - Uptime Kuma:
          href: http://kuma.russlt.com
          icon: sh-uptime-kuma.svg
          server: wanderer
          container: uptime-kuma
          widget:
            type: uptimekuma
            fields: ["up", "down", "uptime"]
            url: http://kuma.skynet.local
            slug: all
      - Proxy:
          href: http://npm.skynet.local
          icon: sh-nginx-proxy-manager.svg
          container: nginproxy
          widget:
            type: npm
            fields: ["enabled", "disabled", "total"]
            url: http://npm.skynet.local
            username: <secret>
            password: <secret>
      - Wondering Wiki:
          icon: sh-wiki-js.svg
          href: http://wiki.russlt.com
          server: wanderer
          container: wikijs-wiki
      - Wiki Database:
          icon: sh-postgresql.svg
          server: wanderer
          container: wikijs-db
  
  - Skynet2:
      - Galaxy:
          href: http://portainer.skynet.local/#!/6/docker/dashboard
          icon: sh-portainer.svg
          container: portainer
          widget:
            type: portainer
            fields: ["running", "stopped", "total"]
            url: http://portainer.skynet.local
            env: 6
            key: <secret>
      - Wanderer (Agent):
          href: http://portainer.skynet.local/#!/7/docker/dashboard
          icon: sh-portainer.svg
          server: wanderer
          container: portainer_agent
          widget:
            type: portainer
            fields: ["running", "stopped", "total"]
            url: http://portainer.skynet.local
            env: 7
            key: <secret>
      - Starbase Delta (Agent):
          href: http://portainer.skynet.local/#!/4/docker/dashboard
          icon: sh-portainer.svg
          server: delta
          container: portainer_agent
          widget:
            type: portainer
            fields: ["running", "stopped", "total"]
            url: http://portainer.skynet.local
            env: 4
            key: <secret>

  - Skynet3:
      - Starbase Delta (Primary DNS):
          href: http://starbase-delta.local/admin
          icon: sh-pi-hole.svg
          widget:
            type: pihole
            fields: ["queries", "blocked", "blocked_percent", "gravity"]
            url: http://starbase-delta.local
            version: 6
            key: <secret>
      - Starbase Epsilon (Secondary DNS):
          href: http://starbase-epsilon.skynet.local
          icon: sh-pi-hole.svg
          container: pihole
          widget:
            type: pihole
            fields: ["queries", "blocked", "blocked_percent", "gravity"]
            url: http://starbase-epsilon.skynet.local
            version: 6
            key: <secret>
      - Nebula Sync:
          icon: sh-pi-hole.svg
          server: delta
          container: nebula-sync
      - IT Tools:
          href: http://ittools.russlt.com
          icon: sh-it-tools.svg
          server: galaxy
          container: ittools

  - Skynet4:
      - Watchtower - Galaxy:
          icon: sh-watchtower.svg
          server: galaxy
          container: watchtower
      - Watchtower - Wanderer:
          icon: sh-watchtower.svg
          server: wanderer
          container: watchtower
      - Watchtower - Delta:
          icon: sh-watchtower.svg
          server: delta
          container: watchtower
      - Skynet Reader:
          href: https://rss.russlt.com
          icon: sh-freshrss.svg
          container: freshrss
          widget:
            type: freshrss
            fields: ["subscriptions", "unread"]
            url: http://rss.skynet.local
            username: <secret>
            password: <secret>

- Calendar:
  - Calendar:
      widget:
        type: calendar
        firstDayInWeek: sunday
        maxEvents: none
        view: monthly
        integrations:
          - type: ical
            url: <secret>
            name: Calendar
  - Agenda:
      widget:
        type: calendar
        view: agenda
        showTime: true
        maxEvents: 10
        integrations:
         - type: ical
           url: <secret>
           name: Agenda

- Bitwarden:
    - Web:
        icon: sh-web-check.png
        server: galaxy
        container: bitwarden-web
    - Admin:
        icon: sh-bitwarden.svg
        server: galaxy
        container: bitwarden-admin
    - Nginx:
        icon: sh-nginx.svg
        server: galaxy
        container: bitwarden-nginx
    - API:
        icon: sh-microsoft-azure.svg
        server: galaxy
        container: bitwarden-api
    - Events:
        icon: sh-nextcloud-calendar.svg
        server: galaxy
        container: bitwarden-events
    - Icons:
        icon: sh-hashicorp-vault.svg
        server: galaxy
        container: bitwarden-icons
    - Identity:
        icon: sh-google.svg
        server: galaxy
        container: bitwarden-identity
    - MSSQL:
        icon: sh-mysql.svg
        server: galaxy
        container: bitwarden-mssql
    - Notifications:
        icon: sh-notifiarr.png
        server: galaxy
        container: bitwarden-notifications
    - Attachments:
        icon: sh-papra.svg
        server: galaxy
        container: bitwarden-attachments
    - SSO:
        icon: sh-microsoft.svg
        server: galaxy
        container: bitwarden-sso