# https://gethomepage.dev/configs/services/

- Skynet Monitoring:
  - Skynet1:
      - Uptime Kuma:
          href: http://kuma.russlt.com
          icon: sh-uptime-kuma.svg
          server: wanderer
          container: uptime-kuma
          widget:
            type: uptimekuma
            fields: ["up", "down", "uptime"]
            url: http://kuma.skynet.local
            slug: all
      - External Proxy:
          href: http://npmw.skynet.local
          icon: sh-nginx-proxy-manager.svg
          server: wanderer
          container: nginproxy
          widget:
            type: npm
            fields: ["enabled", "disabled", "total"]
            url: http://npmw.skynet.local
            username: <secret>
            password: <secret>
      - Internal Proxy:
          href: http://npm.skynet.local
          icon: sh-nginx-proxy-manager.svg
          container: nginproxy
          widget:
            type: npm
            fields: ["enabled", "disabled", "total"]
            url: http://npm.skynet.local
            username: <secret>
            password: <secret>
  
  - Skynet2:
      - Galaxy:
          href: http://portainer.skynet.local/#!/6/docker/dashboard
          icon: sh-portainer.svg
          container: portainer
          widget:
            type: portainer
            fields: ["running", "stopped", "total"]
            url: http://portainer.skynet.local
            env: 6
            key: <secret>
      - Wanderer (Agent):
          href: http://portainer.skynet.local/#!/7/docker/dashboard
          icon: sh-portainer.svg
          server: wanderer
          container: portainer_agent
          widget:
            type: portainer
            fields: ["running", "stopped", "total"]
            url: http://portainer.skynet.local
            env: 7
            key: <secret>
      - Starbase Delta (Agent):
          href: http://portainer.skynet.local/#!/4/docker/dashboard
          icon: sh-portainer.svg
          server: delta
          container: portainer_agent
          widget:
            type: portainer
            fields: ["running", "stopped", "total"]
            url: http://portainer.skynet.local
            env: 4
            key: <secret>

  - Skynet3:
      - Starbase Delta (Primary DNS):
          href: http://starbase-delta.local/admin
          icon: sh-pi-hole.svg
          widget:
            type: pihole
            fields: ["queries", "blocked", "blocked_percent", "gravity"]
            url: http://starbase-delta.local
            version: 6
            key: <secret>
      - Starbase Epsilon (Secondary DNS):
          href: http://starbase-epsilon.skynet.local
          icon: sh-pi-hole.svg
          container: pihole
          widget:
            type: pihole
            fields: ["queries", "blocked", "blocked_percent", "gravity"]
            url: http://starbase-epsilon.skynet.local
            version: 6
            key: <secret>
      - Nebula Sync:
          icon: sh-pi-hole.svg
          server: delta
          container: nebula-sync
      - IT Tools:
          href: http://ittools.skynet.local
          icon: sh-it-tools.svg
          server: galaxy
          container: ittools

  - Skynet4:
      - Watchtower - Galaxy:
          icon: sh-watchtower.svg
          server: galaxy
          container: watchtower
      - Watchtower - Wanderer:
          icon: sh-watchtower.svg
          server: wanderer
          container: watchtower
      - Watchtower - Delta:
          icon: sh-watchtower.svg
          server: delta
          container: watchtower

- Calendar:
  - Calendar:
      widget:
        type: calendar
        firstDayInWeek: sunday
        maxEvents: none
        view: monthly
        integrations:
          - type: ical
            url: <secret>
            name: Calendar

  - Agenda:
      widget:
        type: calendar
        view: agenda
        showTime: true
        maxEvents: 10
        integrations:
         - type: ical
           url: <secret>
           name: Agenda

- Wandering Wiki:
  - WandereWiki:
      - Wiki:
          icon: sh-wiki-js.svg
          href: http://wiki.russlt.com
          server: wanderer
          container: wikijs-wiki
      - Database:
          icon: sh-postgresql.svg
          server: wanderer
          container: wikijs-db

  - FreshRSS:
    - Skynet RSS Reader:
        href: https://rss.russlt.com
        icon: sh-freshrss.svg
        widget:
          type: freshrss
          fields: ["subscriptions", "unread"]
          url: http://rss.skynet.local
          username: <secret>
          password: <secret>