# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

# Basic Site Settings
title: Homepage
language: en
theme: dark
color: slate #zinc
target: _blank
statusStyle: "dot"
useEqualHeights: true
maxBookmarkGroupColumns: 4
headerStyle: boxed
groupsInitiallyCollapsed: false

# Site Assets
base: https://servuce.domain.tld/ #http://service.domain.tld
background:
  image: images/background.png
  blur: xs

########################
#### Home Tab Items ####
########################
layout:
  # HOME Tab Items
  Network:
      style: column
      tab: Home
      icon: mdi-network
  Management:
      style: column
      tab: Home
      icon: mdi-server
  Knowledge Management:
      style: column
      tab: Home
      icon: mdi-book-account
  Media Services:
      style: column
      tab: Home
      icon: mdi-multimedia
  Calendar:
      style: column
      tab: Home
      icon: mdi-calendar-month
  Agenda:
      style: column
      tab: Home
      icon: mdi-view-agenda
  Download Management:
      style: column
      tab: Home
      icon: mdi-download-multiple
  NotUsed2:
      style: column
      tab: Home
      header: false

########################
# Containers Tab Items #
########################
  Security:
      style: row
      columns: 5
      tab: Containers
      icon: mdi-server-security
  Applications:
      style: row
      columns: 5
      tab: Containers
      icon: mdi-application-array-outline
  Tools:
      style: row
      columns: 5
      tab: Containers
      icon: mdi-toolbox-outline
  Bitwarden:
      style: row
      columns: 5
      tab: Containers
      icon: mdi-shield-account-outline