# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

# Basic Site Settings
title: Skynet Homepage
language: en
theme: dark
color: slate
target: _blank
statusStyle: "dot"
useEqualHeights: true
maxBookmarkGroupColumns: 4
headerStyle: boxed
groupsInitiallyCollapsed: false

# Site Assets
base: http://home.skynet.local
background:
  image: images/background.png
  blur: xs

layout:
  Skynet services:
    style: row
    columns: 4
    Skynet1:
      header: false
    Skynet2:
      header: false
    Skynet3:
      header: false
    Skynet4:
      header: false

  Row2:
    style: row
    columns: 4
    header: false
    Col1:
      header: false
    Col2:
      header: false
    Col3:
      header: false
    Col4:
      header: false

  Bitwarden:
    style: row
    columns: 6
    rows: 2
