# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

# Basic Site Settings
title: Homepage
language: en
theme: dark
color: slate
target: _blank
statusStyle: "dot"
useEqualHeights: true
maxBookmarkGroupColumns: 4
headerStyle: boxed
groupsInitiallyCollapsed: false

# Site Assets
base: http://home.domain.tld
background:
  image: images/background.png
  blur: xs

layout:
  Services:
    style: row
    columns: 4
    Zone1:
      header: false
    Zone2:
      header: false
    Zone3:
      header: false
    Zone4:
      header: false

  Row2:
    style: row
    columns: 4
    header: false
    Col1:
      header: false
    Col2:
      header: false
    Col3:
      header: false
    Col4:
      header: false

  Bitwarden:
    style: row
    columns: 6
    rows: 2

  Containers:
    style: row
    columns: 4