# Website: https://freshrss.org/
# Container: https://hub.docker.com/r/freshrss/freshrss
# GitHub: https://github.com/FreshRSS/FreshRSS

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    #ports:
      #- 8090:80
    volumes:
      - /<localpath>/freshrss/data/:/var/www/FreshRSS/data
      - /<localpath>/freshrss/extensions/:/var/www/FreshRSS/extensions
    logging:
      options:
        max-size: 100m
    environment:
      TZ: ${TZ}
      CRON_MIN: ${CRON_MIN}
      TRUSTED_PROXY: ${TRUSTED_PROXY}
    networks:
      - default

volumes:
  data:
  extensions:

networks:
  default:
    external: true
    name: proxnet