# Website: 
#		Transmission: https://transmissionbt.com/
#		Gluetun: https://github.com/qdm12/gluetun-wiki
# Container: 
#		Transmission: https://hub.docker.com/r/linuxserver/transmission
#		Gluetun: https://hub.docker.com/r/qmcgaw/gluetun
# GitHub:
#		Transmission: https://github.com/transmission/transmission
#		Gluetun: https://github.com/qdm12/gluetun

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: service:gluetun
    depends_on:
      gluetun:
          condition: service_healthy
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${LOCALPATH}/transmission/data/:/config # Data directory
      - ${LOCALPATH}/transmissions/:/downloads # Downloads directory
      - ${LOCALPATH}/transmissions/watch/:/watch # Watch directory
    #ports:
    #  - 9091:9091
    #  - 51413:51413
    #  - 51413:51413/udp
    restart: unless-stopped

networks:
  default:
    external: true
    name: vpn